name: youcan_pay
description: A Dart/Flutter SDK for Youcan Pay APIs.
version: 0.8.1
repository: https://github.com/anasfik/youcan_pay
documentation: https://github.com/anasfik/youcan_pay/blob/main/README.md
issue_tracker: https://github.com/anasfik/youcan_pay/issues

environment:
  sdk: ^3.0.0

dependencies:
  equatable: ^2.0.5
  http: ^1.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
